# Generated by Django 5.0.3 on 2025-03-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_connlog_filelog_githubrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrun',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='name'),
        ),
    ]
