# Generated by Django 5.0.3 on 2025-03-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_githubrun_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrun',
            name='platform',
            field=models.CharField(default='', max_length=100, verbose_name='platform'),
        ),
    ]
