# Generated by Django 5.0.3 on 2024-04-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_connlog_action_alter_connlog_conn_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connlog',
            name='conn_id',
            field=models.CharField(max_length=10, null=True, verbose_name='Connection ID'),
        ),
        migrations.AlterField(
            model_name='connlog',
            name='session_id',
            field=models.CharField(max_length=60, null=True, verbose_name='Session ID'),
        ),
    ]
