# Generated by Django 5.0.3 on 2024-04-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_connlog_conn_id_alter_connlog_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileLog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=500, verbose_name='Path')),
                ('sent_from', models.CharField(max_length=20, verbose_name='Sent From ID')),
                ('sent_to', models.CharField(max_length=20, verbose_name='Sent To ID')),
                ('sent_to_ip', models.CharField(max_length=20, verbose_name='Sent To IP')),
                ('logged_at', models.CharField(max_length=35, null=True, verbose_name='Logged At')),
            ],
        ),
        migrations.AlterField(
            model_name='connlog',
            name='logged_at',
            field=models.CharField(max_length=35, null=True, verbose_name='Logged At'),
        ),
    ]
