# Generated by Django 5.0.3 on 2024-04-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_filelog_alter_connlog_logged_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='filelog',
            name='filesize',
            field=models.CharField(default='', max_length=500, verbose_name='Filesize'),
        ),
    ]
