# Generated by Django 5.0.3 on 2024-04-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_filelog_sent_from_remove_filelog_sent_to_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connlog',
            name='logged_at',
        ),
        migrations.AddField(
            model_name='connlog',
            name='conn_end',
            field=models.CharField(default='', max_length=35, null=True, verbose_name='Disconnected'),
        ),
        migrations.AddField(
            model_name='connlog',
            name='conn_start',
            field=models.CharField(default='', max_length=35, null=True, verbose_name='Connected'),
        ),
    ]
