# Generated by Django 5.0.3 on 2024-04-09 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_connlog_logged_at_connlog_conn_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connlog',
            name='conn_end',
            field=models.DateTimeField(null=True, verbose_name='Disconnected'),
        ),
        migrations.AlterField(
            model_name='connlog',
            name='conn_start',
            field=models.DateTimeField(null=True, verbose_name='Connected'),
        ),
        migrations.AlterField(
            model_name='filelog',
            name='logged_at',
            field=models.DateTimeField(null=True, verbose_name='Logged At'),
        ),
    ]
