# Generated by Django 5.0.3 on 2024-04-15 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_rustdeskpeer_hostname_alter_rustdeskpeer_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connlog',
            name='from_id',
            field=models.CharField(max_length=20, null=True, verbose_name='From ID'),
        ),
    ]
