# Generated by Django 5.0.3 on 2024-09-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_rustdesdevice_options_and_more'),
        ('api', '0015_connlog_from_id'),
    ]

    operations = [
    ]
